# Generated by Django 4.2.1 on 2023-05-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.CharField(default='я промуфлонил', max_length=300, verbose_name='Ответ'),
            preserve_default=False,
        ),
    ]
