# Generated by Django 4.2.1 on 2023-05-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzles', '0002_task_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.CharField(choices=[('Math', 'Математика'), ('Fish', 'Рыбки')], max_length=128, unique=True, verbose_name='Категория'),
        ),
    ]
