# Generated by Django 4.2.1 on 2023-05-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzles', '0003_alter_category_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.CharField(default='Общая тема', max_length=100, verbose_name='Тема задачи'),
        ),
    ]
