# Generated by Django 4.2.1 on 2023-05-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzles', '0004_task_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=128)),
                ('score', models.IntegerField(default=0, verbose_name='Счет')),
                ('solved_tasks', models.ManyToManyField(related_name='players', to='quizzles.task')),
            ],
        ),
    ]
