# Generated by Django 4.2.1 on 2023-05-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzles', '0006_alter_player_solved_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
